version: '2'

services:
    monerod:
        env_file: .env
        container_name: monerod
        restart: always
        build: .
        image: monero
        command: |
            monerod --config-file /monero/monerod.conf --non-interactive --confirm-external-bind --rpc-login "${RPC_LOGIN}"
        volumes:
            - "$DATADIR:/monero"
        ports:
            - "${BIND_P2P_PORT}"
            - "${BIND_RPC_PORT}"
    monerowallet:
        env_file: .env
        container_name: monero_wallet
        restart: always
        image: monero
        volumes:
            - "$DATADIR:/monero"
        command: |
            monero-wallet-rpc --config-file /monero/wallet.conf --daemon-login "${RPC_LOGIN}" --rpc-login "${RPC_LOGIN}" --confirm-external-bind
        ports:
            - "${BIND_WALLET_PORT}"


networks:
    default:
        driver: 'bridge'

