version: '2'

services:
    monerod:
        env_file: .env
        container_name: monerod
        restart: always
        build: .
        image: monero
        command: |
            monerod --config-file /monero/monerod.conf --non-interactive --confirm-external-bind --rpc-login "${RPC_LOGIN}"
        volumes:
            - "$PWD/data:/monero"
        ports:
            - "0.0.0.0:18080:18080"
            - "127.0.0.1:18081:18081"
    monerowallet:
        env_file: .env
        container_name: monero_wallet
        restart: always
        image: monero
        volumes:
            - "$PWD/data:/monero"
        command: |
            monero-wallet-rpc --config-file /monero/wallet.conf --password "${WALLET_PASS}" --daemon-login "${RPC_LOGIN}" --rpc-login "${RPC_LOGIN}" --confirm-external-bind
        ports:
            - "127.0.0.1:18100:18100"


networks:
    default:
        driver: 'bridge'
